version: "3.9"

services:
  nats1:
    image: nats:latest
    container_name: nats1-dc2
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./dc2.conf:/etc/nats/nats.conf
    ports:
      - "4221:4222"   # client

  app1:
    image: mrtdeh/nats-client
    tty: true
    stdin_open: true
    container_name: dc2-app1
    environment:
      - NATS_URL=nats://nats1-dc2:4222
      - NAME=app1
      - DC=dc2
    depends_on:
      - nats1

  app2:
    image: mrtdeh/nats-client
    tty: true
    stdin_open: true
    container_name: dc2-app2
    environment:
      - NATS_URL=nats://nats1-dc2:4222
      - NAME=app2
      - DC=dc2
    depends_on:
      - nats1

  app3:
    image: mrtdeh/nats-client
    tty: true
    stdin_open: true
    container_name: dc2-app3
    environment:
      - NATS_URL=nats://nats1-dc2:4222
      - NAME=app3
      - DC=dc2
    depends_on:
      - nats1

# networks:
#   default:
#     name: dc2-network
networks:
  default:
    external: true
    name: nats-net
